#!/bin/bash
#----------------------------------------------------
#SBATCH -J mkl_job       # Job name
#SBATCH -o mkl_job.o%j   # Name of stdout output file(%j expands to jobId)
#SBATCH -e mkl_job.o%j   # Name of stderr output file(%j expands to jobId)
#SBATCH -p development           # Submit to the 'normal' or 'development' queue
#SBATCH -N 1                # Total number of nodes requested (16 cores/node)
#SBATCH -n 1                # Total number of mpi tasks requested
#SBATCH -t 02:00:00         # Run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=kn906@nyu.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes
#SBATCH -A TG-ASC150003    # account number
# #SBATCH -A A-yourproject  # Allocation name to charge job against

# Set the number of threads per task(Default=1)
export OMP_NUM_THREADS=16
export KMP_AFFINITY=granularity=fine,compact,1,0
export MIC_ENV_PREFIX=MIC 
export MIC_KMP_AFFINITY=explicit,granularity=fine,proclist=[1-236:1]
export MIC_OMP_NUM_THREAD=60
export MKL_MIC_DISABLE_HOST_FALLBACK=1

# For Automatic Offloading
export OFFLOAD_REPORT=2

# Run the OpenMP application
./mkl 16384 2;
#./mkl 16384 0;./mkl 8192 2;./mkl 8192 0;./mkl 4096 2;./mkl 4096 0;./mkl 2048 2;./mkl 2048 0;./mkl 1024 2;./mkl 1024 0;./mkl 512 2;./mkl 512 0;./mkl 256 2;./mkl 256 0;./mkl 128 2;./mkl 128 0;./mkl 64 2;./mkl 64 0;
